### ISSUE TITLE
Splash Visual Glitch

### ISSUE THREAD

**Issue by REBBYSETGO** [Ladysnake/Effective#112]
All other particles and effects work fine but for some reason the splash effect only shows up as all black instead of the white and blue color its supposed to be.

**Comment by ZachjuKamashi** [comment]
Can confirm I am also having this exact issue.
![SplashBug](https://user-images.githubusercontent.com/98941240/187543445-033b4225-2e70-4dfe-bb8a-568cb4ac53a1.png)

**Comment by yehun10** [comment]
how to fix?

**Comment by ZachjuKamashi** [comment]
> Can confirm I am also having this exact issue.

Now I didn't post much helpful info yesterday because it was so late, so I will now.
I am playing on fabric 1.19.1
My PC's specifications are: i5-4430S, 16 GB's of RAM, RX 470 4GB GPU, Main storage: 500GB HDD, Secondary Storage, 1TB HDD.
I am running on Linux Mint 20.3 with KDE Plasma desktop environment

Here is a list of all mods I am using and what version they are on: 
Bobby v4.0.0
Chime v1.3.0
cloth-basic-math v0.6.0
Cull Leaves v2.3.4
Effective v1.2.2
Enhanced Block Entities v0.7.1+1.19
EntityCulling-Fabric v1.5.2-mc1.19
Iris v1.2.8
Lithium v0.8.3
MaLiLib v0.13.0
MidnightControls v1.5.0+1.19
Mod Menu v4.0.5
No Chat Reports v1.19.1-v1.8.2
No Fog v1.3.1+1.16.5-1.19.2
Sodium v0.4.4+build.18
Starlight v1.1.1+fabric.ae22326
Tweakeroo v0.14.2
WI Zoom v1.4-MC1.19.1
WorldEdit V7.2.11+c43a877
Xaeros Minimap v22.13.0
Xaeros World Map v1.26.2

Here is also an F3 screenshot for more info if needed.
![More info](https://user-images.githubusercontent.com/98941240/187690417-78d4dbbc-8094-425c-a60b-6810531c2631.png)

**Comment by BlipoHippo** [comment]
same issue, did anyone get it fixed?

**Comment by lonefelidae16** [comment]
> same issue, did anyone get it fixed?

I fixed it in #96. It was not merged, but the code is included in Effective 1.3.

If you are still using Effective 1.2.x and can’t wait for it to be published, please fetch the latest code and try the build.

The prebuilt jar for Effective 1.3 is not available at this time, and I also have no plan to upload the jar to my maven.

**Comment by doctor4t** [comment]
Will be fixed in 1.3
