### ISSUE TITLE
Is fabric still being supported?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Ladysnake/Effective#134]
I saw you said the mod was being migrated over to quilt. Does that mean the mod isn't going to be upgraded on fabric anymore?

**Comment by Morivy** [comment]
Yes, it's quite an unexpected decision on his part, given the very low popularity of Quilt.

**Comment by srnyx** [comment]
Yeah, I'm not a huge fan of this new trend of migrating to Quilt. It was already a huge thing (and still is) for people to migrate from Forge to Fabric. Now it's just gonna be that all over again. 😞

**Comment by Eman-3600** [comment]
I'd say that despite migrating to Quilt working _most_ of the time, I'd say the majority of people don't know anything about Quilt, so most simply won't use it. As a result, migrating any mods from Fabric to Quilt will result in death by obscurity, at least as of right now.

**Comment by srnyx** [comment]
> I'd say that despite migrating to Quilt working _most_ of the time, I'd say the majority of people don't know anything about Quilt, so most simply won't use it.

I think the main issue is that there are just so few mods (at least mainstream ones, 1M+ downloads) that have migrated to Quilt that it's pointless to migrate (unless you only use mods that have migrated).

**Comment by Arathain** [comment]
The argument of "X modloader has no popular mods ergo no popular mods should move to it" is circular and, to put it bluntly, a tad idiotic. I've heard it with Fabric before, and as I did not listen previously I will not listen now. Quilt is a modloader that I can trust the development team of, and thus I develop on it; in the new Effective update, rat is using a library that I maintain, and thus he has to use Quilt, regardless of the fact that he also prefers it over Fabric. There will be no Fabric support, [here](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261)'s a list of quilt-incompatible mods which you can discuss, check, and report, and that's the extent to which this change affects you. Have a good day/night.

**Comment by doctor4t** [comment]
Arathain perfectly explained my point of view. While there's many reasons that I decided to move to Quilt, the one that ultimately made me decide on it is the fact that most Fabric mods have no trouble running on this new loader. I've been thinking about this migration ever since Quilt was announced, but thank you for your input nonetheless.

The popularity of my mods never really mattered to me. I started modding as a hobby, not worrying about whether or not people would use my mods, and I've always strived for it to remain that way; I shall continue doing so for the forseeable future.

I understand your concerns, your fears and your worries; they are valid. But after carefully weighing the pros and cons, I believe this to be the right decision. Thank you for understanding.

**Comment by srnyx** [comment]
> Arathain perfectly explained my point of view. While there's many reasons that I decided to move to Quilt, the one that ultimately made me decide on it is the fact that most Fabric mods have no trouble running on this new loader. I've been thinking about this migration ever since Quilt was announced, but thank you for your input nonetheless.

I didn't know that most Fabric mods worked on Quilt as I was told otherwise a while ago, so that's my bad, sorry.
Thanks for responding! *Now that I know (most) Fabric mods work on Quilt I'd definitely be down to switch to it (once my launcher supports it).*

**Comment by dehen** [comment]
I just made the migration to quilt for another mod (excavated variants). 

I just wanted to give people a frame of reference to people who are considering migrating. I show 170+ jars in my mods folder, and I only had only one incompatibility, and it was a little mod I could do without.

Your mileage may vary, of course, because there's lots of mods out there. It could impact the one mod you just can't live without. I just wanted to put out there that the migration was pretty painless for me, in case other people are considering it.

**Comment by Felix14-v2** [comment]
![Screenshot_20221109-213038](https://user-images.githubusercontent.com/75726196/200912780-015c0dfc-97f6-4e72-a0cc-faa3f996ee3f.jpg)
In addition, dropping Fabric support is a bad solution as long as it is not difficult to maintain compatibility with it. When you drop Fabric in favor of Quilt, it's like you're saying "hey, dude, I hate Fabric and your community".

**Comment by doctor4t** [comment]
Fixed the description, thanks for pointing it out!

**Comment by srnyx** [comment]
> When you drop Fabric in favor of Quilt, it's like you're saying "hey, dude, I hate Fabric and your community".

I disagree, I think it's just easier for them to use Quilt (better framework probably) and they'd rather support Quilt than Fabric (whether that is because they want more people to use Quilt or they just don't like Fabric, it doesn't really matter). I'm not personally offended that they switched to Quilt lmao, I'm just upset (but knowing now that most Fabric mods work with Quilt, I'm okay with the switch, and actually support it now).

**Comment by Boobies** [comment]
Well, if anyone is interested, empirically, this decision effectively (pun intended) killed the mod. Look at the drop in downloads for the Quilt versions, it's several orders of magnitude lower.

**Comment by Felix14-v2** [comment]
> killed the mod

Actually its popularity, but not the mod itself. As the author said, 

> The popularity of my mods never really mattered to me. I started modding as a hobby, not worrying about whether or not people would use my mods, and I've always strived for it to remain that way; I shall continue doing so for the forseeable future.

**Comment by Arathain** [comment]
yes, rat does not rely on this as a source of income, and I don't get any money from this at all, so we *really* don't care that much about downloads.
I ask you all to not comment on this issue unless you have something of actual interest to say (FYI, most of the time, it won't be)

**Comment by srnyx** [comment]
Asking on behalf of anyone that would want to:
If someone were to make a Fabric port of the mod, could they be allowed to upload the mod to mod pages (CurseForge/Modrinth), but under a different name (ex: More Effects, or would you prefer it to use the same name [Effictive - Fabric Port])?

**Comment by Arathain** [comment]
no.
The license does not permit it, and it is quite literally redundant.
