### ISSUE TITLE
Effective incompatibility with ecologics?

### ISSUE THREAD

**Issue by AshBear09** [Ladysnake/Effective#204]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ecologics'!

Im confused because I thought it was supposed to be a client side mod

**Comment by Xiribidus** [comment]
Client side mods can still crash with other mods. However, in order to understand this issue we require the full crash log located in `%AppData%/.minecraft/crash-reports` on your device. Should there not be a crash report please send the related log in `%AppData/.minecraft/logs` (*in this case make sure to not accidentally leak any personal information via the user profile name by censoring it in the log*).

**Comment by AshBear09** [comment]
Thanks for your help. Heres the crash report 
[Ecologics and Effective crash.txt](https://github.com/Ladysnake/Effective/files/12004793/Ecologics.and.Effective.crash.txt)

**Comment by Xiribidus** [comment]
Try installing [Satin API](https://curseforge.com/minecraft/mc-mods/satin-api).
