### ISSUE TITLE
Very poor performance on Vivecraft

### ISSUE THREAD

**Issue by Cubicalspy** [Ladysnake/Effective#209]
I normally have around 70fps without shaders  and without Effective, when I add Effective, it drops to 18fps without any reason. I am not even looking at any effects.

Specs:
RTX 3060ti
AMD Ryzen 5 5600X
16GB Ram - 6GB for Minecraft.

Minecraft 1.19.2
Quilt 0.19.2
Effective 2.1.1

**Comment by Cubicalspy** [comment]
> 

I get 60-70fps with shaders and mods. Effective causes it to drop significantly, 10-20fps. Do you think maybe Sodium, Phosphor or another mod might be interfering?

**Comment by Cubicalspy** [comment]
> 

I get 60-70fps with shaders and mods. Effective causes it to drop significantly, 10-20fps. Do you think maybe Sodium, Phosphor or another mod might be interfering?

**Comment by FaultyFunctions** [comment]
I am also experiencing poor performance with Vivecraft. The only mods installed are:

- Vivecraft v1.20.1-1.1.9 for Fabric/Quilt
- Effective v2.2.1+1.20.1
- QFAPI v7.5.0+0.91.0-1.20.1

My system specs:
- AMD Ryzen 7 3700X
- RTX 3080 10GB
- 32GB RAM (8GB dedicated to MC + ZGC garbage collector enabled)


Without Effective installed I am getting a solid 90 FPS, with it running I am getting around 30 FPS and the CPU is struggling to keep up.

Something to do with how Vivecraft operates with VR mode enabled that Effective hates and tanks FPS. Without Vivecraft enabled, Effective does not affect FPS at all.

Hope this can be fixed because this is an amazing mod for VR immersion. Let me know if there is anything I can try or help with in resolving this, thanks!
