### ISSUE TITLE
Crashes 1.19.2 Fabric

### ISSUE THREAD

**Issue by capasseidk** [Ladysnake/Effective#211]
yes

**Comment by Living-Lemming** [comment]
Fabric isnt supported, this is a [Quilt](https://quiltmc.org/en/) mod

**Comment by Eman-3600** [comment]
Effective does not have a Fabric 1.19.2 release. It instead uses [Quilt](https://quiltmc.org/en/). This is intentional.

**Comment by Xiribidus** [comment]
[It very much does have a fabric 1.19.2 release](https://www.curseforge.com/minecraft/mc-mods/effective/files/4036489)

**Comment by Xiribidus** [comment]
@capasseidk Even though there is a release for the mentioned minecraft version on fabric, we still need the crash log located in %AppData%/.minecraft/crash-reports. If you don't provide said log we will have to close the issue.

_My assumption for the crash would be missing [Satin API](https://www.curseforge.com/minecraft/mc-mods/satin-api) for anybody else wondering_

**Comment by TheRealDanini** [comment]
As @Xiribidus said, you probably did not have all the dependencies, there is a fabric version on curseforge, on the curseforge page check the relations and make sure you download all dependencies that are listed. for me that was [Satin API](https://www.curseforge.com/minecraft/mc-mods/satin-api) that I needed to download because the dependency for it was not listed in modrinth.

So yes, the fabric version does work but you do need to download the dependencies for it.

**Comment by Xiribidus** [comment]
_Actually a good reminder to close this one ^^_
