### ISSUE TITLE
[1.20.1] Effect not compatible with shaders (Iris, Sodium)

### ISSUE THREAD

**Issue by MrCookie112** [Ladysnake/Effective#238]
Hello,
Some visual effects are not compatible with the shaders. I tested this problem with the shaders as well as with previous versions of Effective and Illumination, which worked well with these shaders.

I notice the absence of particles for Firefly, Will-o'-Wisp, enhanced fireball, spectral arrow trail, allay trail, Glowsquid, and dragon breath when I activate a shader with Iris + Sodium. 

video :
https://medal.tv/fr/games/minecraft/clips/1VArBFvsL0mE55/MhHVU6Wx3pSg?invite=cr-MSx6eGksMjE3NzYzNjk5LA

![image](https://github.com/Ladysnake/Effective/assets/97046342/b396488f-d4dd-4e9b-bdbb-9c21ec21d1a1)
![image](https://github.com/Ladysnake/Effective/assets/97046342/60dfa184-ac03-4e29-b121-b36b162340df)

**Comment by cph101** [comment]
This is due to the fact that [lodestonelib-quilt](https://github.com/Arathain/LodestoneLib-Quilt) is being used, which modifies minecraft’s core shaders in order to render particles. The issue also appears with mods using the [original forge version](https://github.com/LodestarMC/Lodestone) and the only existing [public fabric port](https://github.com/cph101/Lodestonelib-fabric). Unfortunately, both Iris and Optifine refuse to add support for these.

**Comment by Xiribidus** [comment]
I'll go ahead and close this as it's not an issue with effective itself
