### ISSUE TITLE
1.21 Port questions

### ISSUE THREAD

**Issue by Dreuzz** [Ladysnake/Effective#277]
Hello I saw that the 1.21 Port branch had some new commits since the last time I checked (3 Weeks ago), I didnt see seem to see a 1.21 Jar tho. I wanted to build it myself but got this error while importing:

```
  Searched in the following locations:
       - file:/home/dreuzzz/Effective/.gradle/loom-cache/remapped_mods/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - file:/home/dreuzzz/.gradle/caches/fabric-loom/minecraftMaven/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - file:/home/dreuzzz/Effective/.gradle/loom-cache/minecraftMaven/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://maven.fabricmc.net/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://libraries.minecraft.net/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://libraries.minecraft.net/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.jar
       - https://repo.maven.apache.org/maven2/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.jar
       - https://repo.maven.apache.org/maven2/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://api.modrinth.com/maven/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://maven.blamejared.com/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://maven.terraformersmc.com/releases/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://maven.ladysnake.org/releases/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://mvn.devos.one/snapshots/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
       - https://mvn.devos.one/releases/top/theillusivec4/curios/curios-neoforge/9.0.9+1.21/curios-neoforge-9.0.9+1.21.pom
     Required by:
         project : > team.lodestar.lodestone:lodestone:1.21.1-1.7.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I tried fixing it but could not manage to.

**Comment by FireInstall** [comment]
Well, Loadstone has not a version for [1.21 ready yet](https://github.com/LodestarMC/Lodestone/issues/44), because it does wait on [porting lib](https://github.com/Fabricators-of-Create/Porting-Lib/tree/1.21.1).
An early version for 1.21 exists though: [1.7.0](https://github.com/LodestarMC/Lodestone/blob/1.21/gradle.properties).
My best guess is that the Lodstone normaly gets pulled from [maven central](https://mvnrepository.com/artifact/team.lodestar.lodestone/lodestone), so try to change the loadstone version to [1.21.1-1.7.0.75](https://mvnrepository.com/artifact/team.lodestar.lodestone/lodestone/1.21.1-1.7.0.75).

This hower comes with a big warning: Please don't expect things to even remotely work. This is NOT a case of an lazy mod author who just dind't uploded their work to a plattform but got a ready-to-use jar ready. Nor is it easy fixable by changing some version numbers and maybe simple complie fixes. There be Dragons!

**Comment by Dreuzz** [comment]
The mod particular is currently my best bet, has most of the features that effective has but for the  current versions.
