### ISSUE TITLE
Volume of Waterfalls don't decrease over distance & Too loud

### ISSUE THREAD

**Issue by Toilet-Man** [Ladysnake/Effective#43]
Here's a video showing the issue (sorry for the bad quality but 10mb isn't much)

https://user-images.githubusercontent.com/76745705/148329306-4eb371ed-8d40-49f7-a990-4c47be33b008.mp4

**Comment by TypicalPretzel** [comment]
this

**Comment by Xastabus** [comment]
I've had to turn ambient sound down to 10% because there's a hidden water flow somewhere "near" my base and the constant noise becomes unbearable.  The distance of this sound seems much further than other minecraft sounds and the volume does not seem to be related to how much water is flowing or how far it may be flowing/falling.

It can be caused by a single block of flowing water in a large volume of source blocks and can sometimes be impossible to find and fill.

Love the splash effects, and the waterfalls would be nice where appropriate... but waterfalls are currently way too loud and frequently generate sound and particles when it isn't entirely appropriate.

**Comment by AM800Mats** [comment]
Tru

**Comment by PernDragon** [comment]
Same Problem, even when I'm not near water I get cascade sound like raining.  Also Lag while traveling the world.
Other than that it's a great mod.

**Comment by drathmorgh** [comment]
I deleted the sound.json and It removed the sounds of the waterfalls but its totally useable now
open with 7zip delete file! fixed
