### ISSUE TITLE
Unexpected error I java.lang.NullPointerException: Cannot invoke "net.minecraft.class_761.method_8568(net.minecraft.class_2394, boolean, double, double, double, double, double, double)" because "this.field_17780" is null

### ISSUE THREAD

**Issue by TheButterbrotMan** [Ladysnake/Effective#48]
Everytime when leaving server,a nd try to join again game crashes. Need to restart to join again.

https://pastebin.com/6cr5ZA91

**Comment by TheButterbrotMan** [comment]
Probably linked to #40

**Comment by AlisterGontineac** [comment]
Was able to load into a world, then decided to start throwing that error "NullPointerException: Cannot invoke "net.minecraft.class_761.method_8568(net.minecraft.class_2394, boolean, double, double, double, double, double, double)" because "this.field_17780" is null"

https://crashy.net/5Oln5Dbfzq4OcY9nsfhd

That other thread has been closed though
