### ISSUE TITLE
No Waterfall Audio

### ISSUE THREAD

**Issue by Ethral-T** [Ladysnake/Effective#81]
I have the following mods installed:
![image](https://user-images.githubusercontent.com/82991477/165231147-f6f6b19d-7606-447b-94eb-2c43a3b1d302.png)
And these following resource packs:
![image](https://user-images.githubusercontent.com/82991477/165231233-b4b0b74c-bd80-49bf-af46-c08b75b39572.png)

When there are cascades, I don't get the ambient sounds that I would have got in previous versions. Is this intentional? Or do I have a conflict somewhere?

**Comment by doctor4t** [comment]
Have you checked the config? You might have changed the option in the past and forgot about it

**Comment by VanderCat** [comment]
Same for me. I disabled all mods but Effective and Quilted Fabric API. No sound, config is default, no RPs.

**Comment by dehen** [comment]
Same for me. Just effective + quilted fab api, default config. Anything after effective 1.3 doesn't give the cascade sound. I've just been sitting on 1.3 because of that.

Like I can take the exact same minecraft instance, same configs, drop in 1.4 or 1.5 and it stops working... put back 1.3 and it works again.

**Comment by doctor4t** [comment]
1.4.1 added a mechanic that makes waterfalls not play sound when not visible, to avoid underground waterfall being heard above surface, but if it removes all waterfall sounds because one block is blocking the view, I'll remove it
